### ISSUE TITLE
"Error: rpmdb open failed"

### ISSUE THREAD

**Issue by daswars** [geerlingguy/docker-centos6-ansible#5]
Hi,
thank you for your great work.

Since the last 8 days I have increased the problem with your docker images
"geerlingguy/docker-centos6-ansible:latest" and a few times with geerlingguy/docker-centos7-ansible:latest following problem: Error: "rpmdb open failed" -> https://www.ostechnix.com/solve-error-rpmdb-open-failed-error-centos/

Can you add the following vlt to the images "rm /var/lib/rpm/__db*" 
or update the images more often? (Every 7 days, at the moment every 14 days)

My problem currently looks like this, here is an example:
````
- name: Ensure lxml is installed for MAVEN Module
  yum:
      pkg: python-lxml
      state: installed
      update_cache: yes
  tags:
      - java
```
I tried it with and without "update_cache: yes"

The problem only occurs from time to time.
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error accessing repos: Error: rpmdb open failed"}
```

Maybe you have an idea how I can solve the problem.
Thank you
Greeting Freddy
